### ISSUE TITLE
Encountered error when purging page cache

### ISSUE THREAD

**Issue by shazzad** [flywp/fly-helper#10]
Upon clicking Clear Cache button, i received the following error (only once):

### Your Site is Experiencing a Technical Issue

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.7.1
Active theme: Blue Maple (version 1.0.0)
Current plugin: FlyWP (version 1.4.0)
PHP version 8.1.30

Error Details
=============
An error of type E_ERROR was caused in line 150 of the file /var/www/html/public/wp-content/plugins/flywp/includes/Admin.php. Error message: Uncaught TypeError: Cannot access offset of type string on string in /var/www/html/public/wp-content/plugins/flywp/includes/Admin.php:150
Stack trace:
#0 /var/www/html/public/wp-content/plugins/flywp/includes/Admin.php(109): FlyWP\Admin->get_site_url('')
#1 /var/www/html/public/wp-includes/class-wp-hook.php(324): FlyWP\Admin->render_admin_page('')
#2 /var/www/html/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /var/www/html/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/html/public/wp-admin/admin.php(259): do_action('dashboard_page_...')
#5 /var/www/html/public/wp-admin/index.php(10): require_once('/var/www/html/p...')
#6 {main}
thrown

![Image](https://github.com/user-attachments/assets/9b4a84c8-8037-40f9-931f-c51592c80ff7)

**Comment by ma-04** [comment]
Hi @shazzad , we were not able to reproduce this issue on our end, please share more information with FlyWP support regarding this.

In the meantime, we will be closing this issue.
